language: java
before_install:
# download jython to use the python scripts for checkstyle
- wget http://search.maven.org/remotecontent?filepath=org/python/jython-standalone/2.7.0/jython-standalone-2.7.0.jar -O jython-standalone-2.7.0.jar
install: 
- mvn -pl "!doc" install -DskipTests=true -Dmaven.javadoc.skip=true -Dcobertura.skip -B -V 
script:
# add login credentials in registry
- java -cp environment/target/tygronenv-*-jar-with-dependencies.jar login.Login $email $password
# test the code
- mvn test -Dcobertura.skip
# test checkstyle only on changed lines using this python script
- git diff master HEAD | java -jar jython-standalone-2.7.0.jar checkstylediff.py
- mvn checkstyle:checkstyle
#check pmd and checkstyle only for environment
- cd environment
- mvn pmd:pmd
- mvn findbugs:findbugs
- cd target
- echo "*PMD-Results*" && cat "java-basic.xml" && cat "java-imports.xml" && cat "java-unusedcode.xml" && echo "PMD-Results END"
- echo "*FINDBUGS-Results*" && cat "findbugsXml.xml" && echo "FINDBUGS-Results END"
- cd ..
# run cobertura only in environment build fails when coverage is too low
- mvn cobertura:check
jdk:
- oraclejdk8
